version: "3.0"

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    env_file:
      - ./auth-service/.env
    volumes:
      - auth_db_data:/app/db
    restart: unless-stopped

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "4000:4000"
    env_file:
      - ./order-service/.env
    volumes:
      - order_db_data:/app/prisma
    depends_on:
      - auth-service
    restart: unless-stopped

  pg-v3-bordeaux:
    image: postgres:16
    container_name: pg-v3-bordeaux
    env_file:
      - ./v3-bordeaux/.env
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=v3_bordeaux
    ports:
      - "5432:5432"
    volumes:
      - v3-bordeaux_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  v3-bordeaux:
    build:
      context: ./v3-bordeaux
    container_name: v3-bordeaux
    ports:
      - "4001:4001"
    env_file:
      - ./v3-bordeaux/.env
    depends_on:
      - pg-v3-bordeaux
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - auth-service
      - order-service
    restart: unless-stopped

volumes:
  auth_db_data:
  order_db_data:
  v3-bordeaux_db_data:
